{{- range .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ tpl .name $ | quote }}
spec:
  refreshInterval: {{ .refreshInterval | default "5m" }}
  secretStoreRef:
    kind: {{ . | dig "secretStoreRef" "kind" "ClusterSecretStore" }}
    name: {{ . | dig "secretStoreRef" "name" "default" }}
  target:
    name: {{ .secretName |default ( tpl .name $ | quote ) }}
  dataFrom:
    {{- tpl (toYaml .dataFrom) $ | nindent 4 }}
{{- end }}