{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ tpl .name $ | quote }}
{{- with .stringData }}
stringData:
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- end }}